server:
  port: 8081
spring:
  application:
    name: account-service
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8084
        register-enabled: false
        watch:
          enabled: false



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMutiQueries=true&serverTimezone=Asia/Shanghai
    username: root  #user01
    password: admin #ak402507979
    hikari:
      connection-timeout: 50000

mybatis:
  mapper-locations: classpath*:config/mybatis/mapper/**/*.xml